---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
  namespace: traefik
data:
  traefik.toml: |
    [Global]
      checkNewVersion = false
      sendAnonymousUsage = false
    [log]
      level = "debug"
    [entryPoints]
      [entryPoints.http]
        address = ":80"
      [entryPoints.https]
        address = ":443"
    [providers]
      [providers.kubernetesCRD]
      # Enable kubernetes ingress provider to expose cert-manager challenge
      [providers.kubernetesIngress]
        ingressClass = "traefik-cert-manager"
    [api]
      dashboard = true
    [ping]
    [metrics]
      [metrics.prometheus]
